In [1]:
import pandas as pd

In [3]:
dados_html = pd.read_html('C:\\Users\\ti_rickelme\\python-fundamentos\\09-Pandas-IO\\04_html_xml\\dados\\AFI\'s 100 Years...100 Movies - Wikipedia.html')

In [4]:
dados_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                       Film  Release year              Director  \
 0             Citizen Kane          1941          Orson Welles
 1               Casablanca          1942        Michael Curtiz
 2            The Godfather          1972  Francis Ford Coppola
 3       Gone with the Wind          1939        Victor Fleming
 4       Lawrence of Arabia          1962            David Lean
 ..                     ...           ...                   ...
 118        Sophie's Choice          1982        Alan J. Pakula
 119  The Last Picture Show          1971     Peter Bogdanovich
 120     Do the Right Thing          1989             Spike Lee
 121           Blade Runner          1982          Ridley Scott
 122              Toy Story          1995         John Lasseter

                               Production companies 1998 Rank 2007 Rank
 0                               RKO Radio Pictures         1         1
 1                            Warner Bros. Pictures         2         3
 2           Paramount Pictures, Alfran Productions         3         2
 3                  Selznick International Pictures         4         6
 4                                 Horizon Pictures         5         7
 ..                                             ...       ...       ...
 118                              ITC Entertainment         -        91
 119                                BBS Productions         -        95
 120                  40 Acres and a Mule Filmworks         -        96
 121                The Ladd Company, Shaw Brothers         -        97
 122  Walt Disney Pictures, Pixar Animation Studios         -        99

 [123 rows x 6 columns]]

In [5]:
type(dados_html)

list

In [7]:
len(dados_html)

2

In [8]:
top_filmes = dados_html[1]

In [9]:
top_filmes

,Film,Release year,Director,Production companies,1998 Rank,2007 Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2,3
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3,2
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4,6
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5,7
...,...,...,...,...,...,...
118,Sophie's Choice,1982,Alan J. Pakula,ITC Entertainment,-,91
119,The Last Picture Show,1971,Peter Bogdanovich,BBS Productions,-,95
120,Do the Right Thing,1989,Spike Lee,40 Acres and a Mule Filmworks,-,96
121,Blade Runner,1982,Ridley Scott,"The Ladd Company, Shaw Brothers",-,97
122,Toy Story,1995,John Lasseter,"Walt Disney Pictures, Pixar Animation Studios",-,99

In [10]:
top_filmes.to_html('top_filmes.html')

In [11]:
top_filmes.to_csv('top_filmes_1998.csv', index=False)

In [13]:
pd.read_csv('C:\\Users\\ti_rickelme\\python-fundamentos\\09-Pandas-IO\\04_html_xml\\top_filmes_1998.csv')

,Film,Release year,Director,Production companies,1998 Rank,2007 Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2,3
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3,2
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4,6
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5,7
...,...,...,...,...,...,...
118,Sophie's Choice,1982,Alan J. Pakula,ITC Entertainment,-,91
119,The Last Picture Show,1971,Peter Bogdanovich,BBS Productions,-,95
120,Do the Right Thing,1989,Spike Lee,40 Acres and a Mule Filmworks,-,96
121,Blade Runner,1982,Ridley Scott,"The Ladd Company, Shaw Brothers",-,97
122,Toy Story,1995,John Lasseter,"Walt Disney Pictures, Pixar Animation Studios",-,99

In [14]:
import pandas as pd

In [16]:
dados_imdb = pd.read_xml('C:\\Users\\ti_rickelme\\python-fundamentos\\09-Pandas-IO\\04_html_xml\\dados\\imdb_top_1000.xml')

In [18]:
dados_imdb.head(3)

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [ ]:
dados_imdb